name: "Hub Mirror Action."
description: "Mirror the organization repos between hub (github/gitee)."
author: "yikun"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  dst_key:
    description: "The private SSH key which is used to to push code in destination hub."
    required: true
  dst_token:
    description: "The app token which is used to  create repo in destination hub."
    required: true
  dst:
    description: "Destination name. Such as `gitee/kunpengcompute`."
    required: true
  src:
    description: "Source name. Such as `github/kunpengcompute`."
    required: true
  account_type:
    description: "The account type. Such as org, user."
    default: 'user'
  clone_style:
    description: "The git clone style, https or ssh."
    default: 'https'
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/hub-mirror-cache'
  black_list:
    description: "Hight priority, the back list of mirror repo. like 'repo1,repo2,repo3'"
    default: ''
  white_list:
    description: "Low priority, the white list of mirror repo. like 'repo1,repo2,repo3'"
    default: ''
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dst_key }}
    - ${{ inputs.dst_token }}
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
    - ${{ inputs.account_type }}
    - ${{ inputs.clone_style }}
    - ${{ inputs.cache_path }}
    - ${{ inputs.black_list }}
    - ${{ inputs.white_list }}
