name: "More Hub Mirror Action."
description: "Mirror the list repos between hub (github/gitee/other)."
author: "Jack"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  dst_key:
    description: "The private SSH key which is used to to push code in destination hub."
    required: true
  dst:
    description: "Destination name. Such as `gitee/kunpengcompute`."
    required: true
  src:
    description: "Source name. Such as `github/kunpengcompute`."
    required: true
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/hub-mirror-cache'
    required: false
  static_list:
    description: "Only mirror repo in the static list, but don't get from repo api (the white/black list is still available). like 'repo1,repo2,repo3'"
    default: ''
    required: true
  force_update:
    description: "Force to update the destination repo, use '-f' flag do 'git push'"
    default: false
    required: false
  debug:
    description: "Enable the debug flag to show detail log"
    default: false
    required: false
  timeout:
    description: "Set the timeout for every git command, like '600'=>600s, '30m'=>30 mins, '1h'=>1 hours"
    default: '30m'
    required: false
  mappings:
    description: "The source repos mappings, such as 'A=>B, C=>CC', source repo name would be mapped follow the rule: A to B, C to CC. Mapping is not transitive."
    default: ''
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dst_key }}
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
    - ${{ inputs.cache_path }}
    - ${{ inputs.static_list }}
    - ${{ inputs.force_update}}
    - ${{ inputs.debug}}
    - ${{ inputs.timeout}}
    - ${{ inputs.mappings}}
